### ISSUE TITLE
Kernel options are requested (scheduling_edf)

### ISSUE THREAD

**Issue by ghost** [gitfri3ndz/foc-lite#1]
Hi @BugUser0815 @StefanEdingerTUM,

during the compilation of genode with the mentioned branch, I got the following output

> \* Restart config...
> \*
> \*
> \* Kernel options
> \*
>Enable multi processor support (MP) [Y/n/?] y
>  Maximal supported number of CPUs (MP_MAX_CPUS) [4] 4
>Fine-grained CPU time (FINE_GRAINED_CPUTIME) [N/y/?] n
> Scheduler
>  1. Fixed priority scheduler (SCHED_FIXED_PRIO)
>  2. Weighted fair queueing scheduler (SCHED_WFQ)
>  3. Combined fixed priority RT and WFQ scheduler (SCHED_FP_WFQ)
> \> 4. Combined fixed priority and Earliest Deadline First scheduler (SCHED_FP_EDF)
>  5. Earliest Deadline First Scheduler (SCHED_EDF) (NEW)
> choice[1-5]: 4

After selecting 4 the compilation process halts.

**Comment by StefanEdingerTUM** [comment]
Hi @dk87 

are you sure you are using the focnados_api branch in genode? 
I cloned it into a new folder and it worked without any changes on the config. 
If you are using another branch, you might need adapt your config according to the one in focnados_api

**Comment by ghost** [comment]
Hi @StefanEdingerTUM 

I'm using the focnados branch and foc edf-scheduler branch. The background, I just want to test your foc changes to the focnados branch as start for merging.

**Comment by StefanEdingerTUM** [comment]
Hi @dk87 
Ok then you might need to adapt your config according to focnados_api
As far as I remember, i did adaptions in 
- /kernel/fiasco/src/Kconfig
- /kernel/fiasco/src/Modules.\*

**Comment by ghost** [comment]
Hi @StefanEdingerTUM  @BugUser0815 

I did a successful merge (focnados_api -> focnados). So far, it compiles without the initial message mentioned above.
