### ISSUE TITLE
EDF thread gets enqueued three times

### ISSUE THREAD

**Issue by BugUser0815** [gitfri3ndz/foc-lite#4]
Relating to https://github.com/argos-research/genode/issues/22
It is obvious that every edf thread is enqueued three times into the ready queue.
Is this a feature or a bug? @dk87

**Comment by ghost** [comment]
it seems like a bug

**Comment by BugUser0815** [comment]
Update:
The platform_thread constructor Stefan Edinger wrote during his IDP calls the following methods:
affinity(location);
_finalize_construction(name);

Where both, the affinity and the _finalize_construction method call l4_scheduler_run_thread.
This explains why the threads are enqueued multiple times.
Yet calling a function twice in Genode does not explain its triple execution within the kernel.

**Comment by ghost** [comment]
okay, what a strange behavior

**Comment by BugUser0815** [comment]
If I remove run_thread from affinity() the thread is enqueued only once \o/

**Comment by BugUser0815** [comment]
This is Genode foo, which has to stay like it was before.
run_thread() within affinity() is ok.
